language: php
php:
  - 5.4
  - 5.5
  - 5.6
#   - hhvm
before_script:
  - phpenv rehash
  - composer install --dev
script:
  - phpunit
cache:
  - vendor
# matrix:
#   fast_finish: true
#   allow_failures:
#     - php: hhvm
#     - php: 5.6
#   exclude:
#     - php: hhvm
#       env: DB=pgsql DB_USER=postgres DB_NAME=postgres  # driver currently unsupported by HHVM
#     - php: hhvm
#       env: DB=sqlite # some issues at the moment
